### ISSUE TITLE
Why do we need to do clamp(delta, lower_limit - X, upper_limit - X)？

### ISSUE THREAD

**Issue by hyserendipity** [locuslab/fast_adversarial#11]

**Comment by AliLotfi92** [comment]
To make sure the input (X+\delta) to the model is in the legitimate interval.

**Comment by hkunzhe** [comment]
They add `transforms.Normalize(mean, std)` in `train_transform` instead of adding normalization layer to the model with nn.Sequential. You can find more details in https://github.com/Harry24k/adversarial-attacks-pytorch/issues/1.
