### ISSUE TITLE
Reproduce the result of CIFAR-10 from the default setting

### ISSUE THREAD

**Issue by baogiadoan** [locuslab/fast_adversarial#17]
Hi, 
I'm running the repo with the default configuration for CIFAR-10, however, here is the reported Accuracy I got from the trained model after 15 epochs: 
```
Total train time: 6.7291 minutes
Test Loss        Test Acc        PGD Loss        PGD Acc
0.9252           **0.7003**          1.2217          **0.3784**
```
so the Accuracy is 70% and PGD Accuracy is only 37.84%? 
Am I missing any detailed configurations?

**Comment by GeJulia** [comment]
Hi I'm facing the same issue. Meanwhile, did you find a way to reproduce the performance reported on CIFAR-10?

**Comment by leslierice1** [comment]
I just re-ran the default configuration for CIFAR-10 and got the following:

```
Total train time: 6.1400 minutes
Test Loss 	 Test Acc 	 PGD Loss 	 PGD Acc
0.6747 	 	 0.7954 	 1.0329 	 0.4490
```

I'm not sure why your results are different -- what does your train loss/accuracy look like over the 15 epochs?
