### ISSUE TITLE
reproduce problem of imagenet on default set

### ISSUE THREAD

**Issue by liuxingbin** [locuslab/fast_adversarial#19]
In table 4. imagenet adversairal robustness result:
method|epsilon|pgd+1restart
---|---|---
|FGSM|2/255|43.46%|
|FGMS|4/255|30.28%|

Is this top5 accuracy or top1 accuracy?

**Comment by riceric22** [comment]
This is Top1 accuracy

**Comment by liuxingbin** [comment]
> This is Top1 accuracy

Thank you for your reply.
however I download the code, and the reproduce result on 4/255 is:
PGD Final Prec@1 6.008 Prec@5 15.540
Final Prec@1 11.500 Prec@5 26.564

Did I miss something? Is any hyper-parameter shouled be changed?
