### ISSUE TITLE
Parameters of training

### ISSUE THREAD

**Issue by DuyguSerbes** [locuslab/fast_adversarial#22]
Hello,

Thanks for your valuable work. 

I would like to understand the methodology behind the division of epsilon and alpha values with standard deviation. 

```
    epsilon = (args.epsilon / 255.) / std
    alpha = (args.alpha / 255.) / std
    pgd_alpha = (2 / 255.) / std
```

**Comment by leslierice1** [comment]
This is due to the fact that the images are already normalized when performing the attack, whereas `args.epsilon` corresponds to the radius for images in the range [0, 1], and so we need to scale epsilon accordingly.
