### ISSUE TITLE
Why not using clean samples during training?

### ISSUE THREAD

**Issue by coordxyz** [locuslab/fast_adversarial#24]
Hi, Does anyone can help me to understand why not using clean samples during training? Will it reduce the performance? Thanks~

**Comment by leslierice1** [comment]
You could try [TRADES](https://github.com/yaodongyu/TRADES), which is a commonly used loss function aimed at reducing the trade-off between robustness and accuracy (using clean and adversarial images), and compare the performance. Training on clean examples during training can sometimes reduce the final model's PGD test accuracy.
