### ISSUE TITLE
About low and high value of uniform distribution in PGD attack (CIFAR-10)

### ISSUE THREAD

**Issue by fugokidi** [locuslab/fast_adversarial#3]
Hi Eric,

Thank you for the code. It's awesome with all efficient training tricks.
I would like to ask your confirmation on the values of low and high value in `CIFAR10/utils.py` line 61, the delta is initialized in uniform distribution on each normalized channel.
```
delta[:, i, :, :].uniform_(-epsilon[i][0][0].item(), epsilon[0][0][0].item())
```
The high value is `epsilon[0][0][0]`, wouldn't it be `epsilon[i][0][0]`?
I am new in this. Can you please confirm? If you specifically fix the high value, can you please explain me a little bit? Thank you for your valuable work again.

**Comment by leslierice1** [comment]
Thanks for noticing this! It was a typo and has been fixed (though it shouldn't matter too much either way).
