### ISSUE TITLE
Imagenet folder miss a lot of files

### ISSUE THREAD

**Issue by TianlongChenTAMU** [locuslab/fast_adversarial#5]
at least the main_free.py, utils and validations

could you please share the missing files?

**Comment by TianlongChenTAMU** [comment]
the command in sh file is:

python main_free.py XXXX

**Comment by riceric22** [comment]
Hi @TianlongChenTAMU, 

The files that you are looking for are in the `utils` folder. You can either move them out of the `utils` folder or add the `utils` folder to your path. Note that the entire structure of the ImageNet repository is a near direct clone of the free adversarial training repository, with minimal changes to perform FGSM training. 

As for `main_free.py`, this is a result of me renaming the file to `main_fast.py` to differentiate it from the free training script in case people were working with both repositories, but I forgot to update the `sh` files. Sorry about that, thanks for bringing it up and I'll update the shell scripts!

**Comment by riceric22** [comment]
Closed with f0cb637a863fb56cb9f1336635faccaed312752b
