### ISSUE TITLE
indices

### ISSUE THREAD

**Issue by AliLotfi92** [locuslab/fast_adversarial#9]
Can anyone please let me know if it's necessary to just update the \deltas of those images that are not misclassified? Can't we just update all \detla s? Which also ensures its maximization. 

https://github.com/locuslab/fast_adversarial/blob/54f728755e71857b632882ba6d6cef22f56e2172/MNIST/train_mnist.py#L95

**Comment by riceric22** [comment]
Hi @AliLotfi92 ! 

For MNIST at epsilon=0.3 in particular, this stabilizes the training procedure (without it in this setting sometimes the training process never learns anything and doesn't converge). You can probably get the same effect without it by tweaking other parameters. 

~Eric
